import { useState } from 'react';
import { Plus, Server, ArrowUpRight, Pencil, Trash2, ArrowUp, ArrowDown, Radio } from 'lucide-react';
import type { Node } from '../types';
import type { Mutate } from './productivity';
import { api } from '../lib/api';
import { Field, Modal, Toggle } from '../components/ui';
export function Nodes({ nodes, mutate, run }: { nodes: Node[]; mutate: Mutate; run: (fn: () => Promise<unknown>) => Promise<void> }) {
  const [editing, setEditing] = useState<Node | null>(null); const [deleting, setDeleting] = useState<Node | null>(null); const [checks, setChecks] = useState<Record<string, string>>({});
  async function move(i: number, d: number) { const list = [...nodes]; const [n] = list.splice(i, 1); list.splice(i + d, 0, n); for (const [sortOrder, node] of list.entries()) if (node.sortOrder !== sortOrder) await mutate({ type: 'saveNode', value: { ...node, sortOrder } }); }
  return <><div className="section-toolbar"><p>使用本机 VS Code Remote - SSH 连接。沿用已有 SSH 配置。</p><button className="button primary" onClick={() => setEditing({ id: crypto.randomUUID(), displayName: '', sshHost: '', enabled: true, sortOrder: nodes.length ? Math.max(...nodes.map(n => n.sortOrder)) + 1 : 0 })}><Plus size={16} />添加节点</button></div><div className="notice">节点入口需要实验室网络（VPN 或已在内网）。TCP 检测仅检查主机名的 22 端口；SSH 别名、自定义端口请以 VS Code 连接结果为准。</div><div className="node-grid">{nodes.map((n, i) => <article className={`card node-card ${!n.enabled ? 'disabled-card' : ''}`} key={n.id}><div className="node-top"><div className="node-symbol"><Server size={21} /></div><span className="tag">{n.enabled ? 'SSH' : '已禁用'}</span></div><h2>{n.displayName}</h2><code>{n.sshHost}</code><div className="node-check"><button className="text-btn" disabled={!n.enabled} onClick={() => { void run(async () => { setChecks(s => ({ ...s, [n.id]: '检测中…' })); try { const ok = await api.probeNode(n.id); setChecks(s => ({ ...s, [n.id]: ok ? 'TCP 22 可达' : 'TCP 22 不可达' })); } catch (e) { setChecks(s => ({ ...s, [n.id]: '检测未完成' })); throw e; } }); }}><Radio size={13} />{checks[n.id] ?? '检测连通性'}</button></div><button className="button secondary node-open" disabled={!n.enabled} onClick={() => { void run(() => api.openNode(n.id)); }}>VS Code <ArrowUpRight size={15} /></button><div className="node-actions"><button className="icon-btn" aria-label={`${n.displayName}上移`} disabled={i === 0} onClick={() => { void move(i, -1); }}><ArrowUp size={14} /></button><button className="icon-btn" aria-label={`${n.displayName}下移`} disabled={i === nodes.length - 1} onClick={() => { void move(i, 1); }}><ArrowDown size={14} /></button><span className="grow" /><button className="icon-btn" aria-label={`编辑节点 ${n.displayName}`} onClick={() => setEditing(n)}><Pencil size={14} /></button><button className="icon-btn danger" aria-label={`删除节点 ${n.displayName}`} onClick={() => setDeleting(n)}><Trash2 size={14} /></button></div></article>)}</div>{!nodes.length && <div className="empty">暂无节点，点击“添加节点”开始配置。</div>}
    {editing && <Modal title="节点配置" onClose={() => setEditing(null)}><form onSubmit={e => { e.preventDefault(); void mutate({ type: 'saveNode', value: editing }).then(saved => { if (saved) setEditing(null); }); }}><Field label="显示名称"><input required maxLength={200} value={editing.displayName} onChange={e => setEditing({ ...editing, displayName: e.target.value })} /></Field><Field label="SSH Host / 已有别名"><input required pattern="[A-Za-z0-9][A-Za-z0-9._-]*" maxLength={253} placeholder="vipsl10" value={editing.sshHost} onChange={e => setEditing({ ...editing, sshHost: e.target.value })} /></Field><Toggle label="启用节点" checked={editing.enabled} onChange={v => setEditing({ ...editing, enabled: v })} /><div className="form-actions"><button className="button primary">保存节点</button></div></form></Modal>}
    {deleting && <Modal title="删除节点入口" onClose={() => setDeleting(null)}><p>删除「{deleting.displayName}」的本地入口？</p><div className="form-actions"><button className="button danger-button" onClick={() => { void mutate({ type: 'deleteNode', value: deleting.id }).then(saved => { if (saved) setDeleting(null); }); }}>删除</button></div></Modal>}
  </>;
}
