import { useEffect, useState } from 'react';
import { Plus, Pencil, Trash2, CalendarDays, Clock3, Check } from 'lucide-react';
import type { CalendarEvent, Mutation, Todo } from '../types';
import { dateTime, localInput, pendingTodos } from '../lib/logic';
import { desktop } from '../lib/api';
import { Empty, Field, Modal } from '../components/ui';
export type Mutate = (m: Mutation) => Promise<boolean>;
export function TodoCard({ todos, mutate }: { todos: Todo[]; mutate: Mutate }) {
  const [editing, setEditing] = useState<Todo | null>(null); const [title, setTitle] = useState(''); const [all, setAll] = useState(false);
  const visible = all ? todos : pendingTodos(todos);
  async function add(e: React.SubmitEvent) { e.preventDefault(); if (!title.trim()) return; if (await mutate({ type: 'saveTodo', value: { id: crypto.randomUUID(), title: title.trim(), completed: false, dueDate: null } })) setTitle(''); }
  return <section className="card todo-card"><div className="card-head"><h2><Check size={18} />Todo <span className="count">{pendingTodos(todos).length}</span></h2><button className="text-btn" onClick={() => setAll(!all)}>{all ? '仅未完成' : '查看全部'}</button></div>
    <form className="quick-add" onSubmit={e => { void add(e); }}><Plus size={17} /><input aria-label="新增 Todo" placeholder="添加一件待办事项…" maxLength={200} value={title} onChange={e => setTitle(e.target.value)} /><button className="text-btn" disabled={!title.trim()}>添加</button></form>
    <div className="todo-list">{visible.map(t => <div className={`todo-row ${t.completed ? 'completed' : ''}`} key={t.id}><input aria-label={`完成 ${t.title}`} type="checkbox" checked={t.completed} onChange={() => { void mutate({ type: 'saveTodo', value: { ...t, completed: !t.completed } }); }} /><div className="grow"><span>{t.title}</span>{t.dueDate && <small>截止 {t.dueDate}</small>}</div><button className="icon-btn" aria-label={`编辑 ${t.title}`} onClick={() => setEditing(t)}><Pencil size={14} /></button><button className="icon-btn danger" aria-label={`删除 ${t.title}`} onClick={() => { void mutate({ type: 'deleteTodo', value: t.id }); }}><Trash2 size={14} /></button></div>)}</div>
    {!visible.length && <div className="quiet-empty">{all ? '还没有 Todo，写下今天的第一件事。' : '没有未完成事项，留一点时间思考。'}</div>}
    {editing && <Modal title="编辑 Todo" onClose={() => setEditing(null)}><form onSubmit={e => { e.preventDefault(); void mutate({ type: 'saveTodo', value: editing }).then(saved => { if (saved) setEditing(null); }); }}><Field label="事项"><input required maxLength={200} value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} /></Field><Field label="截止日期（可选）"><input type="date" value={editing.dueDate ?? ''} onChange={e => setEditing({ ...editing, dueDate: e.target.value || null })} /></Field><div className="form-actions"><button className="button primary">保存</button></div></form></Modal>}
  </section>;
}
function newEvent(): CalendarEvent { const now = new Date(); now.setMinutes(0, 0, 0); now.setHours(now.getHours() + 1); return { id: crypto.randomUUID(), title: '', startsAt: now.toISOString(), endsAt: new Date(now.getTime() + 3600000).toISOString(), notes: '', remindAt: null, notifiedAt: null }; }
export function Calendar({ events, mutate, compact = false }: { events: CalendarEvent[]; mutate: Mutate; compact?: boolean }) {
  const [editing, setEditing] = useState<CalendarEvent | null>(null); const [filter, setFilter] = useState('upcoming');
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 60000); return () => clearInterval(timer); }, []);
  const upcoming = events.filter(e => new Date(e.endsAt).getTime() >= now);
  const shown = compact ? upcoming.slice(0, 3) : filter === 'all' ? events : upcoming;
  return <section className={`card ${compact ? 'schedule-card' : ''}`}><div className="card-head"><h2><CalendarDays size={18} />{compact ? '近期日程' : '本地日程'}</h2><div className="row">{!compact && <select aria-label="日程筛选" value={filter} onChange={e => setFilter(e.target.value)}><option value="upcoming">即将到来</option><option value="all">全部日程</option></select>}<button className="text-btn" onClick={() => setEditing(newEvent())}><Plus size={15} />新建日程</button></div></div>
    {shown.length ? <div className="event-list">{shown.map(e => <article className="event-row" key={e.id}><div className="date-block"><small>{new Date(e.startsAt).getMonth() + 1} 月</small><strong>{new Date(e.startsAt).getDate()}</strong></div><div className="grow"><strong>{e.title}</strong><small><Clock3 size={12} />{dateTime(e.startsAt)} — {dateTime(e.endsAt)}</small>{!compact && e.notes && <p>{e.notes}</p>}{e.remindAt && <small>{e.notifiedAt ? '已提醒' : `提醒：${dateTime(e.remindAt)}`}</small>}</div><button className="icon-btn" aria-label={`编辑日程 ${e.title}`} onClick={() => setEditing(e)}><Pencil size={14} /></button><button className="icon-btn danger" aria-label={`删除日程 ${e.title}`} onClick={() => { void mutate({ type: 'deleteEvent', value: e.id }); }}><Trash2 size={14} /></button></article>)}</div> : <Empty title="暂无近期日程" text="组会、实验安排和截止时间，都可以记在这里。" />}
    {editing && <Modal title="日程安排" onClose={() => setEditing(null)}><form onSubmit={e => { e.preventDefault(); void mutate({ type: 'saveEvent', value: editing }).then(saved => { if (saved) setEditing(null); }); }}><Field label="标题"><input required maxLength={200} value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} /></Field><div className="two-fields"><Field label="开始时间"><input required type="datetime-local" value={localInput(editing.startsAt)} onChange={e => { if (e.target.value) setEditing({ ...editing, startsAt: new Date(e.target.value).toISOString() }); }} /></Field><Field label="结束时间"><input required type="datetime-local" value={localInput(editing.endsAt)} onChange={e => { if (e.target.value) setEditing({ ...editing, endsAt: new Date(e.target.value).toISOString() }); }} /></Field></div><Field label="提醒时间（可选）"><input type="datetime-local" value={editing.remindAt ? localInput(editing.remindAt) : ''} onChange={e => setEditing({ ...editing, remindAt: e.target.value ? new Date(e.target.value).toISOString() : null })} /></Field><Field label="备注"><textarea rows={3} maxLength={20000} value={editing.notes} onChange={e => setEditing({ ...editing, notes: e.target.value })} /></Field><p className="muted">{desktop ? "应用在托盘中运行时仍会提醒；完全退出后无法提醒。" : "需保持网页和本机后端运行。关闭网页或浏览器休眠期间不保证及时提醒。"}</p><div className="form-actions"><button className="button primary">保存日程</button></div></form></Modal>}
  </section>;
}
