import { useState } from 'react';
import { Plus, ArrowUpRight, Star, Pin, Pencil, Trash2, LockKeyhole, ArrowUp, ArrowDown, LayoutGrid } from 'lucide-react';
import type { Service } from '../types';
import type { Mutate } from './productivity';
import { Empty, Field, Modal, Toggle } from '../components/ui';
export function ServiceCards({ services, open }: { services: Service[]; open: (s: Service) => void }) {
  return <div className="service-grid">{services.map((s, i) => <button className="service-tile" disabled={!s.enabled} key={s.id} onClick={() => open(s)}><div className={`service-icon color-${i % 4}`}>{s.icon || s.name.slice(0, 1).toUpperCase()}</div><div className="grow"><strong>{s.name}</strong><small>{new URL(s.url).host}</small></div>{s.requiresVpn && <LockKeyhole size={13} className="muted" />}<ArrowUpRight size={16} /></button>)}</div>;
}
export function Services({ services, mutate, open }: { services: Service[]; mutate: Mutate; open: (s: Service) => void }) {
  const [editing, setEditing] = useState<Service | null>(null); const [deleting, setDeleting] = useState<Service | null>(null);
  function add() { setEditing({ id: crypto.randomUUID(), name: '', url: '', icon: '', requiresVpn: true, favorite: true, pinnedToSidebar: false, sortOrder: services.length ? Math.max(...services.map(s => s.sortOrder)) + 1 : 0, enabled: true }); }
  async function move(i: number, d: number) { const items = [...services]; const [s] = items.splice(i, 1); items.splice(i + d, 0, s); for (const [sortOrder, item] of items.entries()) if (item.sortOrder !== sortOrder) await mutate({ type: 'saveService', value: { ...item, sortOrder } }); }
  return <><div className="section-toolbar"><p>实验室 Web 服务，集中访问、各自登录。</p><button className="button primary" onClick={add}><Plus size={16} />添加服务</button></div>{services.length ? <div className="card table-card"><table><thead><tr><th>服务</th><th>访问方式</th><th>常用 / 侧栏</th><th>顺序</th><th>管理</th></tr></thead><tbody>{services.map((s, i) => <tr key={s.id}><td><button className="service-name" onClick={() => open(s)} disabled={!s.enabled}><span className="mini-icon">{s.icon || <LayoutGrid size={16} />}</span><span><strong>{s.name}</strong><small>{s.url}</small></span></button></td><td><span className="tag">{s.requiresVpn ? 'VPN 内网' : '直接访问'}</span>{!s.enabled && <span className="tag">已禁用</span>}</td><td><button aria-label={`${s.name}常用`} className={`icon-btn ${s.favorite ? 'selected' : ''}`} onClick={() => { void mutate({ type: 'saveService', value: { ...s, favorite: !s.favorite } }); }}><Star size={16} /></button><button aria-label={`${s.name}固定到侧栏`} className={`icon-btn ${s.pinnedToSidebar ? 'selected' : ''}`} onClick={() => { void mutate({ type: 'saveService', value: { ...s, pinnedToSidebar: !s.pinnedToSidebar } }); }}><Pin size={16} /></button></td><td><button aria-label={`${s.name}上移`} disabled={i === 0} className="icon-btn" onClick={() => { void move(i, -1); }}><ArrowUp size={15} /></button><button aria-label={`${s.name}下移`} disabled={i === services.length - 1} className="icon-btn" onClick={() => { void move(i, 1); }}><ArrowDown size={15} /></button></td><td><button aria-label={`编辑服务 ${s.name}`} className="icon-btn" onClick={() => setEditing(s)}><Pencil size={15} /></button><button aria-label={`删除服务 ${s.name}`} className="icon-btn danger" onClick={() => setDeleting(s)}><Trash2 size={15} /></button></td></tr>)}</tbody></table></div> : <section className="card"><Empty title="添加实验室的第一个服务" text="例如 gpustat、Nezha、ClearML 或 New API。使用管理员提供的真实地址。" action="添加服务" onAction={add} /></section>}
    {editing && <Modal title="服务配置" onClose={() => setEditing(null)}><form onSubmit={e => { e.preventDefault(); void mutate({ type: 'saveService', value: editing }).then(saved => { if (saved) setEditing(null); }); }}><div className="two-fields"><Field label="服务名称"><input required maxLength={200} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /></Field><Field label="图标（文字或 Emoji）"><input maxLength={16} value={editing.icon} onChange={e => setEditing({ ...editing, icon: e.target.value })} placeholder="C" /></Field></div><Field label="服务入口 URL"><input required type="url" placeholder="https://clearml.example.org" value={editing.url} onChange={e => setEditing({ ...editing, url: e.target.value })} /></Field><p className="muted">使用不含账号、密码、查询参数和片段的 HTTP/HTTPS 入口地址。</p><Toggle label="需要 VPN" checked={editing.requiresVpn} onChange={v => setEditing({ ...editing, requiresVpn: v })} /><Toggle label="显示在首页常用服务" checked={editing.favorite} onChange={v => setEditing({ ...editing, favorite: v })} /><Toggle label="固定到侧栏" checked={editing.pinnedToSidebar} onChange={v => setEditing({ ...editing, pinnedToSidebar: v })} /><Toggle label="启用服务" checked={editing.enabled} onChange={v => setEditing({ ...editing, enabled: v })} /><div className="form-actions"><button className="button primary">保存服务</button></div></form></Modal>}
    {deleting && <Modal title="删除服务" onClose={() => setDeleting(null)}><p>删除「{deleting.name}」的本地入口？此操作不会删除服务端数据。</p><div className="form-actions"><button className="button secondary" onClick={() => setDeleting(null)}>取消</button><button className="button danger-button" onClick={() => { void mutate({ type: 'deleteService', value: deleting.id }).then(saved => { if (saved) setDeleting(null); }); }}>删除</button></div></Modal>}
  </>;
}
