import { useState, type ReactNode } from 'react';
import { Download, Upload, Bell, RefreshCw, ArrowUpRight } from 'lucide-react';
import type { Settings as SettingsModel, UpdateInfo } from '../types';
import type { Mutate } from './productivity';
import { api, desktop } from '../lib/api';
import { Field, Toggle } from '../components/ui';
export function Settings({ settings, mutate, run, refresh, vpnCard, navigate }: { settings: SettingsModel; mutate: Mutate; run: (fn: () => Promise<unknown>) => Promise<void>; refresh: () => Promise<void>; vpnCard: ReactNode; navigate: (id: string) => void }) {
  const [draft, setDraft] = useState(settings); const [update, setUpdate] = useState<UpdateInfo | null>(null); const [notification, setNotification] = useState(''); const [fileMessage, setFileMessage] = useState('');
  return <div className="settings-stack"><section className="card"><div className="card-head"><h2>常规</h2><span className="tag">本地设置</span></div><div className="card-content">{desktop ? <><Toggle label="开机自动启动 Worktable" hint="默认关闭，独立于 VPN 自动连接。" checked={settings.autostart} onChange={v => { void mutate({ type: 'saveSettings', value: { ...settings, autostart: v } }); }} /><Toggle label="启动后直接进入托盘" checked={settings.startInTray} onChange={v => { void mutate({ type: 'saveSettings', value: { ...settings, startInTray: v } }); }} /><Toggle label="启动时自动连接上次 VPN" hint="仅使用上次选择的本机配置。" checked={settings.vpnAutoconnect} onChange={v => { void mutate({ type: 'saveSettings', value: { ...settings, vpnAutoconnect: v } }); }} /></> : <p className="notice">当前为网页版。无需安装桌面应用；托盘、开机启动和 VPN 自动连接设置将在桌面版中提供。</p>}<div className="settings-action"><span>日程通知<small>{notification || (desktop ? '请允许通知，以便在托盘中接收提醒。' : '网页内提醒默认启用。允许浏览器通知后可显示系统提醒；需保持网页和本机后端运行。')}</small></span><button className="button secondary" onClick={() => { void run(async () => { const result = await api.notifyPermission(); setNotification(result === 'Granted' ? '已允许通知' : result === 'Denied' ? '通知已拒绝，请前往系统设置开启。' : '通知权限尚未确定'); }); }}><Bell size={15} />允许通知</button></div></div></section>
    {vpnCard}
    <section className="card"><div className="card-head"><h2>服务与节点</h2></div><div className="card-content two-fields"><button className="button secondary" onClick={() => navigate('services')}>管理 Web 服务<ArrowUpRight size={16} /></button><button className="button secondary" onClick={() => navigate('nodes')}>管理计算节点<ArrowUpRight size={16} /></button></div></section>
    <section className="card"><div className="card-head"><h2>实验室配置</h2><span className="tag">schema v1</span></div><div className="card-content"><form onSubmit={e => { e.preventDefault(); void mutate({ type: 'saveSettings', value: { ...settings, labName: draft.labName, clusterHealthCheckUrl: draft.clusterHealthCheckUrl, updateEndpoint: draft.updateEndpoint } }); }}><Field label="实验室名称"><input required value={draft.labName} maxLength={200} onChange={e => setDraft({ ...draft, labName: e.target.value })} /></Field><Field label="集群连通性检查 URL"><input required type="url" value={draft.clusterHealthCheckUrl} onChange={e => setDraft({ ...draft, clusterHealthCheckUrl: e.target.value })} /></Field><Field label="版本检查 endpoint（可选，HTTPS）"><input type="url" placeholder="https://worktable.example.org/releases.json" value={draft.updateEndpoint} onChange={e => setDraft({ ...draft, updateEndpoint: e.target.value })} /></Field><div className="form-actions"><button className="button primary">保存公共设置</button></div></form><hr /><p className="muted">配置包共享服务、节点和公共设置。导入将替换现有服务与节点；不包含 VPN、Todo、日程、Cookie 或登录信息。</p><div className="row"><button className="button secondary" onClick={() => { void run(async () => { const ok = await api.importLab(); if (ok) { await refresh(); setFileMessage('实验室配置已导入。'); } }); }}><Upload size={15} />导入配置包</button><button className="button secondary" onClick={() => { void run(async () => { if (await api.exportLab()) setFileMessage('实验室配置已导出。'); }); }}><Download size={15} />导出 lab-config.json</button></div>{fileMessage && <p role="status">{fileMessage}</p>}</div></section>
    <section className="card"><div className="card-head"><h2>版本信息</h2><span className="tag">0.1.0</span></div><div className="card-content"><div className="settings-action"><span>HYKSJ Worktable<small>科研课题组的一站式工作台</small></span><button className="button secondary" onClick={() => { void run(async () => setUpdate(await api.checkUpdate())); }}><RefreshCw size={15} />检查更新</button></div>{update && <div className="update-info"><strong>{update.available ? `发现新版本 ${update.version}` : '当前已是最新版本'}</strong><p>{update.releaseNotes}</p>{update.available && update.downloadUrl && <button className="button primary" onClick={() => { void run(() => api.openDownload(update.downloadUrl!)); }}>打开下载页面<ArrowUpRight size={16} /></button>}</div>}<p className="muted">第一版仅检查版本，下载由你手动完成。{desktop ? "Web 数据清理将在后续版本加入。" : "服务登录数据由浏览器管理。"}</p></div></section>
  </div>;
}
