import { Shield, Upload, Unplug, ArrowRight, Pencil, Trash2 } from 'lucide-react';
import { useState } from 'react';
import type { Capability, VpnProfile, VpnStatus } from '../types';
import { canConnect, vpnLabels } from '../lib/logic';
import { api, desktop } from '../lib/api';
import { Field, Modal } from '../components/ui';
import type { Mutate } from './productivity';
export function VpnCard({ profiles, status, capability, selected, select, run, refresh, management = false, mutate }: { profiles: VpnProfile[]; status: VpnStatus; capability: Capability | null; selected: string; select: (id: string) => void; run: (fn: () => Promise<unknown>) => Promise<void>; refresh: () => Promise<void>; management?: boolean; mutate: Mutate }) {
  const [health, setHealth] = useState('未检测'); const [editing, setEditing] = useState<VpnProfile | null>(null); const [deleting, setDeleting] = useState<VpnProfile | null>(null);
  const connected = status.state === 'Connected'; const idle = canConnect(status.state);
  return <section className="card vpn-card"><div className="card-head"><h2><Shield size={18} />实验室网络</h2><span className={`status-pill ${connected ? 'connected' : ''}`}><span className={`dot ${connected ? 'green' : ''}`} />{vpnLabels[status.state]}</span></div><div className="vpn-body"><div className={`vpn-emblem ${connected ? 'online' : ''}`}><Shield size={28} /></div><div className="grow"><h3>{connected ? '已接入实验室网络' : status.state === 'Failed' ? '连接未完成' : idle ? '连接，让工作就绪' : vpnLabels[status.state]}</h3><p>{status.message}</p></div></div><div className="vpn-controls"><select aria-label="VPN 配置" value={selected} disabled={!idle} onChange={e => select(e.target.value)}><option value="">{profiles.length ? '选择 VPN 配置' : '尚未导入 .ovpn 配置'}</option>{profiles.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select>{idle ? <button className="button primary" disabled={!selected || !capability?.available} onClick={() => { void run(async () => { await api.connect(selected); await refresh(); }); }}>连接 VPN<ArrowRight size={15} /></button> : <button className="button secondary" disabled={status.state === 'Disconnecting'} onClick={() => { void run(() => api.disconnect()); }}><Unplug size={15} />断开</button>}<button className="button secondary" onClick={() => { void run(async () => { await api.importVpn(); await refresh(); }); }}><Upload size={15} />导入 .ovpn</button></div>{capability && !capability.available && <p className="inline-note">{capability.detail}</p>}<div className="vpn-footer"><span>OpenVPN · {capability?.source ?? '检测 backend…'}</span><button className="text-btn" onClick={() => { void run(async () => { setHealth('检测中…'); const ok = await api.health(); setHealth(ok ? '集群入口可达' : '集群入口不可达'); }); }}>{health} · 检测集群</button></div>
    {!desktop && <p className="inline-note">VPN 由本机后端管理；也可使用已有 VPN 客户端。集群检测成功仅表示内网可达，不代表 Worktable 建立了隧道。</p>}
    {management && <div className="profile-list">{profiles.map(p => <div className="profile-row" key={p.id}><Shield size={15} /><span className="grow">{p.name}</span><button className="icon-btn" aria-label={`重命名 ${p.name}`} onClick={() => setEditing(p)}><Pencil size={14} /></button><button className="icon-btn danger" aria-label={`删除配置 ${p.name}`} onClick={() => setDeleting(p)}><Trash2 size={14} /></button></div>)}<p className="muted">配置保存在本机私有目录。导出实验室配置包不会包含 VPN 文件。</p></div>}
    {editing && <Modal title="重命名 VPN 配置" onClose={() => setEditing(null)}><form onSubmit={e => { e.preventDefault(); void mutate({ type: 'renameProfile', value: editing }).then(saved => { if (saved) setEditing(null); }); }}><Field label="显示名称"><input required maxLength={200} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /></Field><div className="form-actions"><button className="button primary">保存</button></div></form></Modal>}
    {deleting && <Modal title="删除 VPN 配置" onClose={() => setDeleting(null)}><p>将删除「{deleting.name}」在 Worktable 中的私有副本，原始文件不受影响。</p><div className="form-actions"><button className="button danger-button" onClick={() => { void run(async () => { await api.deleteVpn(deleting.id); await refresh(); setDeleting(null); }); }}>删除配置</button></div></Modal>}
  </section>;
}
