import { Shield, Upload, Unplug, ArrowRight, Pencil, Trash2 } from 'lucide-react';
import { useState } from 'react';
import type { Capability, VpnProfile, VpnStatus } from '../types';
import { canConnect, vpnLabels } from '../lib/logic';
import { api, desktop } from '../lib/api';
import { VpnUpload } from './vpn-upload';
import { Field, Modal } from '../components/ui';
import type { Mutate } from './productivity';
export function VpnCard({ profiles, status, capability, selected, select, run, refresh, mutate }: { profiles: VpnProfile[]; status: VpnStatus; capability: Capability | null; selected: string; select: (id: string) => void; run: (fn: () => Promise<unknown>) => Promise<void>; refresh: () => Promise<void>; management?: boolean; mutate: Mutate }) {
  const [authProfile, setAuthProfile] = useState<string | null>(null);
  const [username, setUsername] = useState(''); const [password, setPassword] = useState('');
  const [uploading, setUploading] = useState(false);
  const [health, setHealth] = useState('未检测'); const [editing, setEditing] = useState<VpnProfile | null>(null); const [deleting, setDeleting] = useState<VpnProfile | null>(null);
  const connected = status.state === 'Connected'; const idle = canConnect(status.state);
  return <section className="card vpn-card"><div className="card-head"><h2><Shield size={18} />实验室网络</h2><span className={`status-pill ${connected ? 'connected' : ''}`}><span className={`dot ${connected ? 'green' : ''}`} />{vpnLabels[status.state]}</span></div><div className="vpn-body"><div className={`vpn-emblem ${connected ? 'online' : ''}`}><Shield size={28} /></div><div className="grow"><h3>{connected ? '已接入实验室网络' : status.state === 'Failed' ? '连接未完成' : idle ? '连接，让工作就绪' : vpnLabels[status.state]}</h3><p>{status.message}</p></div></div><div className="vpn-controls"><select aria-label="VPN 配置" value={selected} disabled={!idle} onChange={e => select(e.target.value)}><option value="">{profiles.length ? '选择 VPN 配置' : '尚未导入 .ovpn 配置'}</option>{profiles.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select>{idle ? <button className="button primary" disabled={!selected || !capability?.available} onClick={() => { void run(async () => { if (!desktop && await api.authRequired(selected)) { setAuthProfile(selected); return; } await api.connect(selected); await refresh(); }); }}>连接 VPN<ArrowRight size={15} /></button> : <button className="button secondary" disabled={status.state === 'Disconnecting'} onClick={() => { void run(() => api.disconnect()); }}><Unplug size={15} />断开</button>}<button className="button secondary" onClick={() => { if (!desktop) setUploading(true); else void run(async () => { await api.importVpn(); await refresh(); }); }}><Upload size={15} />导入 .ovpn</button></div>{capability && !capability.available && <p className="inline-note">{capability.detail}</p>}<div className="vpn-footer"><span>OpenVPN · {capability?.source ?? '检测 backend…'}</span><button className="text-btn" onClick={() => { void run(async () => { setHealth('检测中…'); const ok = await api.health(); setHealth(ok ? '集群入口可达' : '集群入口不可达'); }); }}>{health} · 检测集群</button></div>
    {!desktop && <p className="inline-note">VPN 由本机后端管理；也可使用已有 VPN 客户端。集群检测成功仅表示内网可达，不代表 Worktable 建立了隧道。</p>}
    <div className="vpn-profiles"><div className="vpn-profiles-heading"><strong>本地 VPN 配置 <span>{profiles.length}</span></strong><button className="text-btn" onClick={() => { if (!desktop) setUploading(true); else void run(async () => { await api.importVpn(); await refresh(); }); }}><Upload size={14} />添加配置</button></div>
      {!profiles.length && <p className="vpn-profile-empty">还没有配置。可一次选择或拖入多个 .ovpn 文件。</p>}
      <div className="vpn-profile-options" role="radiogroup" aria-label="选择用于连接的 VPN 配置">{profiles.map(p => <div className={`vpn-profile-option${selected === p.id ? ' selected' : ''}`} key={p.id}>
        <label><input type="radio" name="vpn-profile" checked={selected === p.id} disabled={!idle} onChange={() => select(p.id)} /><Shield size={20} /><span><strong>{p.name.toLowerCase().endsWith('.ovpn') ? p.name : `${p.name}.ovpn`}</strong><small>{status.profileId === p.id && !idle ? vpnLabels[status.state] : selected === p.id ? '已选择 · 用于下次连接' : '保存在本机'}</small></span></label>
        <button className="icon-btn" aria-label={`重命名 ${p.name}`} onClick={() => setEditing(p)}><Pencil size={14} /></button><button className="icon-btn danger" aria-label={`删除配置 ${p.name}`} disabled={status.profileId === p.id && !idle} onClick={() => setDeleting(p)}><Trash2 size={14} /></button>
      </div>)}</div>
      {!idle && <p className="muted">切换配置前请先断开当前连接。</p>}
      <p className="vpn-local-note">文件仅保存在本机私有目录，不上传 GitHub，也不包含在配置导出中。</p>
    </div>
    {authProfile && <Modal title="VPN 账号认证" onClose={() => { setAuthProfile(null); setUsername(''); setPassword(''); }}><form onSubmit={e => { e.preventDefault(); const id = authProfile; const credentials = { username, password }; setPassword(''); setUsername(''); setAuthProfile(null); void run(async () => { await api.connect(id, credentials); await refresh(); }); }}><p className="muted">此配置需要 VPN 账号密码。仅用于本次连接，不保存到文件或数据库。</p><Field label="VPN 用户名"><input required autoComplete="off" value={username} onChange={e => setUsername(e.target.value)} /></Field><Field label="VPN 密码"><input required type="password" autoComplete="off" value={password} onChange={e => setPassword(e.target.value)} /></Field><div className="form-actions"><button className="button primary">连接 VPN</button></div></form></Modal>}
    {uploading && <Modal title="上传 VPN 配置" onClose={() => setUploading(false)}><VpnUpload refresh={refresh} /></Modal>}
    {editing && <Modal title="重命名 VPN 配置" onClose={() => setEditing(null)}><form onSubmit={e => { e.preventDefault(); void mutate({ type: 'renameProfile', value: editing }).then(saved => { if (saved) setEditing(null); }); }}><Field label="显示名称"><input required maxLength={200} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /></Field><div className="form-actions"><button className="button primary">保存</button></div></form></Modal>}
    {deleting && <Modal title="删除 VPN 配置" onClose={() => setDeleting(null)}><p>将删除「{deleting.name}」在 Worktable 中的私有副本，原始文件不受影响。</p><div className="form-actions"><button className="button danger-button" onClick={() => { void run(async () => { await api.deleteVpn(deleting.id); await refresh(); setDeleting(null); }); }}>删除配置</button></div></Modal>}
  </section>;
}
